USE [master]
GO

/****** Object:  Database [Stepify]    Script Date: 2/8/2018 9:24:54 AM ******/
CREATE DATABASE [Stepify]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Stepify', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Stepify.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Stepify_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Stepify_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Stepify] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Stepify].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Stepify] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Stepify] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Stepify] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Stepify] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Stepify] SET ARITHABORT OFF 
GO

ALTER DATABASE [Stepify] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Stepify] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Stepify] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Stepify] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Stepify] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Stepify] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Stepify] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Stepify] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Stepify] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Stepify] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Stepify] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Stepify] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Stepify] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Stepify] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Stepify] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Stepify] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Stepify] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Stepify] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Stepify] SET RECOVERY FULL 
GO

ALTER DATABASE [Stepify] SET  MULTI_USER 
GO

ALTER DATABASE [Stepify] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Stepify] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Stepify] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Stepify] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Stepify] SET  READ_WRITE 
GO

